services:
        web:
                image: flask_alexa_v1  # identifiable name for shared machine
                build: .
                ports:
                        - "8088:8080" # port distinct from others
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/AlexaFlaskPython/volumes  # name consistent with repo